Hh hw
tikhcloud/hh-school-2020-java-collections-stream pull request #1
Opened 2020-12-04 15:28 UTC by tikhcloud

### Task 6

Был самым сложным, пытался решить без создания мапы, но так и не придумал как это сделать (возможно, это не возможно).

### Task 8

_Код, который был, не удалял, просто закоментил_

`List<String> getNames(List<Person> person)`
* Использовал тернарный оператор, потому что так можно и так красивее.
* В коллекции List, есть метод `isEmpty()`, лучше использовать его, а не `persons.size() == 0`, потому что `isEmpty()`,
 вне зависимости от размера контейнера - **O(n)**, в то время как `.size()` - **O(1)**
* Вместо того, чтобы удалять первый элемент коллекции и двигать все элементы по индексу влево,
 первый элемент можно просто пропустить используя `.skip(1)`
 
`Set<String> getDifferentNames(List<Person> persons)`
* `distinct()` - не нужен, stream и так будет distinct.
* Как и в прошлом методе использую тернарный оператор, для того чтобы проверить - пустая ли коллекция, 
если нет то пропускаю первую персону, потому что: _"Не хотим выдывать апи нашу фальшивую персону"_, 
дальше прохожу по всем персонам и Set сам отсечет одинаковые персоны - потому что в Set все элементы уникальны.
 
`String convertPersonToString(Person person)`
* Два раза `secondName`? там я думаю имелось ввиду `middleName`.
* Собираю в список, фильтрую **null** объекты
 
`Map<Integer, String> getPersonNames(Collection<Person> persons)`
* Используем предыдущий метод, для отображения полного имени и в мапу переводим с помощью коллектора.
 
`boolean hasSamePersons(Collection<Person> persons1, Collection<Person> persons2)`
* Тут вообще можно сделать одной строчкой с помощью Collections.disjoint()
из документации: _"Returns true if the two specified collections have no elements in common."_
 
`long countEven(Stream<Integer> numbers)`
* Используя фильтр, проверяю что остаток равен нулю.

`boolean check()`
* =)

2020-12-05 20:47 UTC, genroelgvozo requested changes

2020-12-05 20:47 UTC, genroelgvozo commented on src/tasks/Task1.java
> +    //O(n)
ну во-первых не O(n), это же сортировка -  n log n
Во-вторых ты сделал не то) Прочти еще раз задание внимательно)

2020-12-05 20:47 UTC, genroelgvozo commented on src/tasks/Task2.java
> +    return Stream.concat(persons1.stream(), persons2.stream())
здесь все ок)

2020-12-05 20:47 UTC, genroelgvozo commented on src/tasks/Task3.java
> +    return persons.stream()
тут все ок

2020-12-05 20:47 UTC, genroelgvozo commented on src/tasks/Task4.java
> +    return persons.stream()
все ок)

2020-12-05 20:47 UTC, genroelgvozo commented on src/tasks/Task5.java
> +    return persons.stream()
все ок)

2020-12-05 20:47 UTC, genroelgvozo commented on src/tasks/Task6.java
>    private Set<String> getPersonDescriptions(Collection<Person> persons,
самое норм решение, без мапы O(n) не сделать, памятью приходится жертвовать (но такая себе жертва, а ускорение сильное)

2020-12-05 20:47 UTC, genroelgvozo commented on src/tasks/Task7.java
> +    return companies.stream()
все гуд) можно даже
.map(Company::getVacancies).flatMap(Collection::stream).map(Vacancy::getTitle)

2020-12-05 20:47 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return persons.isEmpty() ? Collections.emptyList() :
а зачем проверка если скип юзаешь?)
и чем плох ремув принципиально?
PS на будущее, лучше вот так к строкам оставлять комменты, а не в описании к пр (во-первых на него мне надо все время переключаться + на его отдельные пункты не ответишь)

2020-12-05 20:47 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return Stream.of(person.getSecondName(), person.getFirstName(), person.getSecondName())
тут все гуд)

2020-12-05 20:47 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return persons.stream()
почти гуд, но твой код будет иногда падать, увы. Ифчик в коде должен был на кое-что намекнуть... (он корявый, но написан не зря)

2020-12-05 20:47 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return !Collections.disjoint(persons1, persons2);
ок, но какая скорость? от чего зависит, и как сделать чтобы всегда было быстро? (в оригинальном коде всегда медленно)

2020-12-05 20:47 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return numbers.filter(num -> num % 2 == 0).count();
ты в пр написал что используешь фильтр, но фильтр и так был в коде) чем плох был изначальный forEach и инкремент?

2020-12-07 03:31 UTC, tikhcloud commented on src/tasks/Task8.java
> +    return persons.isEmpty() ? Collections.emptyList() :
Проверку убрал.
Ремув плох тем, что он удалит значение из переданной в метод коллекции. persons - ссылочная переменная.

2020-12-07 04:13 UTC, tikhcloud commented on src/tasks/Task1.java
> +            .map(idToPersons::get)
##Исправил
Асимптотика работы O(n)
обход множества персон и преобразование в мапу O(n)
Получение значения из мапы O(1), добавление значений в список O(1)

2020-12-07 04:13 UTC, tikhcloud commented on src/tasks/Task7.java
> +    return companies.stream()
Поправил)

2020-12-07 04:13 UTC, tikhcloud commented on src/tasks/Task8.java
> +    return persons.stream()
Проверку убрал.
Ремув плох тем, что он удалит значение из переданной в метод коллекции. persons - ссылочная переменная.

2020-12-07 04:13 UTC, tikhcloud commented on src/tasks/Task8.java
> +    return persons.stream()
Исправил

Если айдишки одинаковые, то код падал (у мапы все ключи должны быть уникальными). Для этого использую функцию мерджа

2020-12-07 04:13 UTC, tikhcloud commented on src/tasks/Task8.java
> +    return persons1.stream().anyMatch(persons2::contains);
disjoint медленно - он пройдется по всей коллекции, в то время как anyMatch() вернет значение true, как только найдет совпадение. «lazy evaluation»

2020-12-07 04:13 UTC, tikhcloud commented on src/tasks/Task8.java
> +    return numbers.filter(num -> num % 2 == 0).count();
В документации про .forEach() написано: 

> For parallel stream pipelines, this operation does not guarantee to respect the encounter order of the stream…

То есть смысл, я так понимаю в этом? Если в метод кинуть параллельный стрим, то он может выдать не правильные значения

2020-12-09 20:16 UTC, genroelgvozo approved these changes

2020-12-09 20:16 UTC, genroelgvozo commented on src/tasks/Task1.java
> +            .map(idToPersons::get)
все гуд)

2020-12-09 20:16 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return persons.stream()
да, пользователь этого не ожидает)

2020-12-09 20:16 UTC, genroelgvozo commented on src/tasks/Task8.java
> +                    .collect(Collectors.toSet());
такс, есть функция с внутренней логикой, своими костылями, и нам надо взять имена и выбрать различные.. И вместо переиспользования кода мы копируем к себе код этой фукнции?)
А если потом еще логика накрутится, и кто-то придет править getNames, он должен вспомнить что еще где-то есть такой же код? Он как раз инкапсулирован, и нам не хочется знать как getNames работает..

2020-12-09 20:16 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return persons.stream()
гуд

2020-12-09 20:16 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return persons1.stream().anyMatch(persons2::contains);
оба медленно, оба могут быть O(n^2), про быстрый выход не надо думать, быстрее будет в лучшем случае, но не в среднем. А вот как быстро всегда? О(n) можно (сейчас иногда тоже так может, но надо сделать чтобы всегда было, независимо от чего-то...)

2020-12-09 20:16 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return numbers.filter(num -> num % 2 == 0).count();
ага) ну тут даже не про ордер (он то не важен в каком порядке прибавим единицу), а про одновременную прибавку, два потока вычисляют count+1, получают одно и тоже число (а должно было быть на 2 больше) и сетят в переменную - операция не атомарная

2021-09-01 09:05 UTC, closed without merging